export default {
      "stepOneHeader" : "Step 1",
      "stepOneText" : "Please enter your email address.",
      "emailPlaceholder":"Email address",
      "submitEmailButtonText":"Continue",
      "registerLinkText": "Not registered?",
      "stepTwoHeader" : "Step 2",
      "stepTwoText" : "Enter the 6-digit code sent to your email",
      "submitCodeButtonText":"Continue",
      "stepThreeHeader" : "Step 3",
      "stepThreeText" : "Please enter new password.",
      "passwordPlaceholder":"Enter new password",
      "confirmPasswordPlaceholder":"Confirm new password",
      "submitPasswordButtonText":"Update Password",
      "emailPatternErrorText":"Email is invalid. Valid format: user@site.com",
      "checkCodeErrorText":"All %s characters must be entered!'",
      "passwordMinLengthErrorText":"Password must be %s characters minimum!",
      "passwordMaxLengthErrorText":"Password must be %s characters maximum!",
      "passwordMatchErrorText":"Passwords do not match."
};
