export default {
      "title" : "Fil par %s",
      "defaultUser": "Utilisateur du forum",
      "unknowUserText" : "Utilisateur inconnu",
      "threadEditButtonText" : "Modifier",
      "threadSaveButtonText" : "Sauvegarder",
      "threadDeleteButtonText" : "Effacer",
      "repliesNumberText" : "%s réponse(s)",
      "replyLinkText":"Écrire une réponse",
      "composerInputPlaceholder":"Écrivez votre réponse ici ...",
      "submitButtonText":"Envoyer une réponse",
      "clearButtonText":"Clair",
      "loginButtonText" : "Connectez-vous pour écrire une réponse",
      "loginDisplayButtonText":"Connectez-vous pour afficher le fil",
      "replyDeleteConfirmationText":"Êtes-vous sûr de vouloir supprimer cette réponse?",
      "threadDeleteConfirmationText" : "Êtes-vous sûr de vouloir supprimer ce fil?",
      "commentTimeNowText" : "À présent",
      "commentTimeSecondsText" : "Il y a %s seconde(s)",
      "commentTimeMinutesText" : "Il y a %s minute(s)",
      "commentTimeHoursText" : "Il y a %s heure(s)",
      "commentTimeDaysText" : "Il y a %s jour(s)",
      "commentTimeWeeksText" : "Il y a %s semaine(s)",
      "commentTimeMonthsText" : "Il y a %s mois",
      "commentTimeYearsText" : "Il y a %s an(s)",
};